# Foundry Configuration File
# See more config options at: https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
optimizer = true
optimizer_runs = 200
libs = ['lib']
src = 'src'
test = 'tests'
out = 'out'
solc = "0.8.19"

[rpc_endpoints]
ethereum = "${RPC_ETHEREUM_URL}"
polygon = "${RPC_POLYGON_URL}"

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "single"
tab_width = 2
wrap_comments = true


ignored_error_codes = ["unreachable", "unused-return", "unused-param", "unused-var", "code-size", "shadowing", "func-mutability", "license", "pragma-solidity", "virtual-interfaces", "same-varname"]
deny_warnings = false